### PR TITLE
Compilation Fixes for Windows

### PR DESCRIPTION
**Pull request by Guillaume227**
Two fixes for compilation failures seen on Windows 10, QT 5.9.0, MSVC 2015, 32 bits
- Declare M_PI in case it's not included in math.h
- c-style array initialized from a local variable are not strictly c++ compliant (although g++ might allow it) - new them instead.

### CODE REVIEW

**Comment by rpasichnyk** [comment]
@Guillaume227 Try defining `_USE_MATH_DEFINES` before including `<cmath>`, this seems to be a better solution 👍 
https://stackoverflow.com/questions/26065359/m-pi-flagged-as-undeclared-identifier
https://stackoverflow.com/questions/6563810/m-pi-works-with-math-h-but-not-with-cmath-in-visual-studio

**Comment by Guillaume227** [comment]
Thanks for the suggestion, I have tried adding the #define _USE_MATH_DEFINES but it's not working for me (using Visual 2017).
I noticed in the stackoverflow comments that someone is stating it's not working for them with Visual 2015.

**Comment by arBmind** [comment]
@Guillaume227 Just add this below the `!android: { }` block to the vesc_tool.pro:
```cpp
win32: {
    DEFINES += _USE_MATH_DEFINES
}
```
You may remove your custom M_PI define. (Tested with VS2017)

**Comment by delete-all** [comment]
Hey guys, do you have a Visual Studio project file or CMake file for the vesc-tool? I have very low c++ skills and I can't get to build it on my laptop; neither with VS nor with Eclipse... Any help/hint would be appreciated...

**Comment by Teslafly** [comment]
I have had success using windows subsystem for Linux (wsl),and following these instructions in the wsl terminal:
https://vesc-project.com/node/310
Vscode even has wsl integrations so there should be a good amount of resources out there for it.

**Comment by delete-all** [comment]
> I have had success using windows subsystem for Linux (wsl),and following these instructions in the wsl terminal:
> https://vesc-project.com/node/310
> Vscode even has wsl integrations so there should be a good amount of resources out there for it.

Hi Teslafly, did you reply to me? :) I went through the tutorial. I understood that Qt could help. But I couldn't install it as it requires 50GB free disk space :/ So, do you confirm that if I had Qt installed, I could build the VESC-tool?

Many thanks!

**Comment by Teslafly** [comment]
> 

yes. installing qt / qtcreator on windows lets you build vesc tool just fine.
all you need is the Qt_5_15_2_MinGW_64_bit toolchain and qtcreator. a lot of the other things can be unselected to get the size down to ~10gb (still alot, but not 50gb)

either way these changes are pretty stale now.

**Pull request closed without merging**
