### PR TITLE
running build_lin deletes all files in ../..

### PR DESCRIPTION
**Pull request by jerkey**
this script needs attention before it can be distributed, since running it will delete all files in ../.. with unconfirmed rm -rf

### CODE REVIEW

**Comment by vedderb** [comment]
The problem is if the cd to build/lin fails, but since I have added set -e to the beginning the script should stop if that happens. Did you experience any problems with it?

**Comment by jerkey** [comment]
> The problem is if the cd to build/lin fails, but since I have added set -e to the beginning the script should stop if that happens. Did you experience any problems with it?

yes I experienced problems with it, it deleted my entire $HOME/hack/ directory.  You can't just throw around commands like this:
ls | grep -v '\.zip$' | xargs rm

**Comment by vedderb** [comment]
There was this issue before:

https://github.com/vedderb/vesc_tool/issues/18

after which I added set -e as suggested, which should stop the script if any commands fail. Did you experience the same problem even after that?

**Comment by jerkey** [comment]
> There was this issue before:
> 
> #18
> 
> after which I added set -e as suggested, which should stop the script if any commands fail. Did you experience the same problem even after that?

no, i had pulled Jul 23 2018, so I did not have that commit yet when I ran the script.  Unlucky for me i guess.

**Pull request closed without merging**
