### PR TITLE
Save and load last connection type, tcp server and port

### PR DESCRIPTION
**Pull request by rpasichnyk**
Last connection type, tcp server and port are lost on exit. Save them to QSettings and load next time.

### CODE REVIEW

**Comment by rpasichnyk** [comment]
hi Benjamin, can you please have a look at this?

**Comment by rpasichnyk** [comment]
Conflicts resolved👍

**Comment by vedderb** [comment]
Nice addition! I'm not completely happy with the implementation though.

The problem I see is that when the last connection is set to none (which is the case without this patch), a serial connection will be made with the first port that is listed with listserialports. However, this implementation will store the last connection as serial, and try to connect to mLastSerialPort on the next start, which will fail as it is an empty string. I see two solutions:

1) When the serial port was used, set the last connection to none to get the default behavior.
2) Store the last serial port (and baud in case someone actually uses UART) to the settings as well, and remember it in the same way as the TCP settings.

I think 2) is a better solution. If it is implemented, storing the settings should probably be handled in vesc_interface, and not in the connection page. Remembering the BLE address could also be useful, but I think it is better to set the last connection to none when BLE was used.

Can you have a look at that, and  maybe share some thoughts about a reasonable behavior?

**Comment by rpasichnyk** [comment]
I will have a look, thank you for the input

**Comment by rpasichnyk** [comment]
Reworked to also include last BLE or serial connection

**Comment by vedderb** [comment]
Looks good as far as I can tell from the diff, I really like it! Thanks!

**Pull request merged**
