### PR TITLE
Use isTestFW as a BETA subversion and display it in Firmware page

### PR DESCRIPTION
**Pull request by Peemouse**
From @Jfriesen222 's original idea. 👍 
This helps beta testers to identify beta versions they're testing.
This helps the dev to target a subversion when a tester reports an issue.

### CODE REVIEW

**Comment by Mitchlol** [comment]
int isTestFw  :rage: 

If you're using it as subversion, how about calling it subversion :angel:

**Comment by Peemouse** [comment]
I'm agree, that's not nice. I wanted to keep the original name though.

**Comment by Peemouse** [comment]
Oh and I didn't mention that if isTestFw == 0, then the FW is considered as stable.
So testing it like a boolean still makes sense.

**Comment by vedderb** [comment]
Nice, thanks!

**Pull request merged**
