### PR TITLE
TCP_NODELAY for client

### PR DESCRIPTION
**Pull request by ddosoff**
I made simple ESP32 based Vesc UART <-> Esp32 WiFi AP bridge.

This small change improves responsiveness a lot if connected via WiFi.

### CODE REVIEW

**Comment by ddosoff** [comment]
Hello Benjamin,

I do not want to create new PR, because this one still not merged.

Here you read https://github.com/vedderb/vesc_tool/blob/master/vescinterface.cpp#L79 settings with default address "127.0.0.1". This is correct.

But a bit later you read settings again:

https://github.com/vedderb/vesc_tool/blob/master/vescinterface.cpp#L141 with empty default address "". This is incorrect and duplicate.

Please remove lines 141 and 142. This is duplicate reading from config.

Feel unhappy with my PRs still without answer (

**Comment by vedderb** [comment]
Thanks for the observation, I will fix it (should not change the behavior much though).

Regarding the PR, there already is a one second timeout in commands, that will ignore requests if an ongoing request is already pending. Adding additional logic for the same thing in mainwindow is not really nice. Also, I would like to understand what the TCP_NODELAY option does and why it is not activated by default before adding it, and I haven't had an opportunity to look into it yet.

Regarding responding, I am completely overwhelmed in general with people contacting me at the moment. Answering all my emails, phone calls, forum posts in the vesc project and my old vedder forums would easily take more than all the time I have available, which makes it impossible. I understand that it can be frustrating to not get a response for a long time or ever, but currently I'm pushing myself as much as I can. All I can do at this point is ask you to not take it personally.

**Comment by ddosoff** [comment]
TCP_NODELAY have to be set for each new socket. I checked real responsiveness with my WiFi bridge.

About mainwindow. Vesc_tool sends requests after connection without answers. On slow channels like LoRa (I did this bridge too) this requests blocks channel and vesc_tool can't connect. My fix solves this issue.

**Comment by vedderb** [comment]
As I wrote, the config read requests are not sent from commands if the last request sent within one second hasn't received a reply yet, regardless of how fast mainwindow tries to poll them. The 1 second timeout on commands can be changed from there, which will affect several commands. I'm not sure that I want to increase it to 3 seconds though, as 1 second seems to be enough even over BLE on low UART baud rates.

I read a bit about TCP_NODELAY, and it might actually be useful here:
https://www.extrahop.com/company/blog/2016/tcp-nodelay-nagle-quickack-best-practices/
The change in mainwindow I don't like though, as I want to have that logic in commands as it is now; and again, I'm not sure if I want to change the timeout to as much as 3 seconds.

**Comment by ddosoff** [comment]
Please check motor reaction of original vesc_tool and patched with TCP_NODELAY for clients sockets: https://www.youtube.com/watch?v=zpEXdvvlT0U

**Pull request closed without merging**
