### PR TITLE
Rename label from "temp hum" to "temp bms"

### PR DESCRIPTION
**Pull request by surfdado**
this has been driving me nuts for a while - am I misunderstanding something or does my proposed change make sense?

### CODE REVIEW

**Comment by vedderb** [comment]
Temp hum is the temperature of the humidity sensor (on hardware that has one).

**Comment by surfdado** [comment]
@vedderb ping

**Comment by Relys** [comment]
This always confused me. Glad I'm not the only one. XD

**Comment by surfdado** [comment]
@vedderb ?

**Comment by vedderb** [comment]
I still don't agree on that naming. Why would temp bms be the temperature of the humidity sensor when there are so many other sensors that measure temperature too?

**Comment by surfdado** [comment]
> I still don't agree on that naming. Why would temp bms be the temperature of the humidity sensor when there are so many other sensors that measure temperature too?

I still think that for the average user "temp hum" is meaningless, took me weeks to figure out. Most wouldn't know that this refers to the temperature of their BMS. As far as I'm concerned "temp bms" is still the most appropriate label, as it is usually the one and only temperature telling you how hot your BMS is, it just happens to be part of the humidity sensor.

**Comment by vedderb** [comment]
The issue is that what I usually care about when it comes to the BMS temperature is how hot the balancing resistors are or the charge switch is (the critical temperature of the BMS itself). The 12s7p has a sensor near the balancing resistors and the 18s light bms has one near the charge switch. The humidity sensor is deliberately placed far away from things that get hot as higher temperature makes the relative humidity go down, so it will measure the least critical temperature.

**Comment by surfdado** [comment]
Okay, I understand now, sounds like the user-defined temp sensors can also be used on the BMS. However, I still wish we had a way to make it more obvious to the user which temperature are related to the BMS temp versus the cell temps.

**Pull request closed without merging**
